---
abstract: 'Add test failures if warnings are caught'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Capture::Tiny: 0.12
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0.96
  blib: 0
  constant: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-FailWarnings
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Test::FailWarnings:
    file: lib/Test/FailWarnings.pm
    version: 0.006
requires:
  Carp: 0
  Test::More: 0.86
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/test-failwarnings/issues
  homepage: https://metacpan.org/release/Test-FailWarnings
  repository: git://github.com/dagolden/test-failwarnings.git
version: 0.006
x_authority: cpan:DAGOLDEN
